{{- if .Values.statefulset.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "common.names.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  {{- range $key, $value := .Values.service.ports }}
    - name: {{ $key }}
      targetPort: {{ $key }}
      {{- toYaml $value | nindent 6 }}
    {{- end }}
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.metrics.service.port }}
      targetPort: metrics
    {{- end }}
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
{{- end -}}
