chart-dirs:
  - ygqygq2
chart-repos:
  - ygqygq2=https://ygqygq2.github.io/charts
check-version-increment: true
debug: true
remote: origin
target-branch: master
validate-chart-schema: true
validate-maintainers: false
validate-yaml: true
