apiVersion: v1
kind: Service
metadata:
  name: {{ template "mysql-servicemonitor.fullname" . }}
  labels:
    app: {{ template "mysql-servicemonitor.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    {{- if .Values.additionalServiceLabels }}
{{ toYaml .Values.additionalServiceLabels | indent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.metricsPort }}
      targetPort: {{ .Values.metricsPort }}
      protocol: TCP
      name: "{{ .Values.metricsPortName }}"
