{{- if and .Values.gateway.enabled .Values.gateway.tls.enabled }}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: {{ include "common.names.fullname" . }}-tls
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if or .Values.gateway.tls.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.gateway.tls.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.gateway.gatewayClassName }}
  parentRefs:
    - name: {{ .Values.gateway.gatewayClassName }}
      {{- if .Values.gateway.namespace }}
      namespace: {{ .Values.gateway.namespace }}
      {{- end }}
      {{- if .Values.gateway.sectionName }}
      sectionName: {{ .Values.gateway.sectionName }}
      {{- end }}
  {{- end }}
  {{- if .Values.gateway.tls.hostnames }}
  hostnames:
    {{- range .Values.gateway.tls.hostnames }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.gateway.tls.rules }}
    - backendRefs:
        {{- range .backendRefs }}
        - name: {{ .name | default (include "common.names.fullname" $) }}
          {{- if .namespace }}
          namespace: {{ .namespace }}
          {{- end }}
          port: {{ .port | default $.Values.service.ports.http.port }}
          {{- if .weight }}
          weight: {{ .weight }}
          {{- end }}
        {{- end }}
    {{- end }}
{{- end }}
