{{- if and .Values.gateway.enabled .Values.gateway.http.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if or .Values.gateway.http.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.gateway.http.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.gateway.gatewayClassName }}
  parentRefs:
    - name: {{ .Values.gateway.gatewayClassName }}
      {{- if .Values.gateway.namespace }}
      namespace: {{ .Values.gateway.namespace }}
      {{- end }}
      {{- if .Values.gateway.sectionName }}
      sectionName: {{ .Values.gateway.sectionName }}
      {{- end }}
  {{- end }}
  {{- if .Values.gateway.http.hostnames }}
  hostnames:
    {{- range .Values.gateway.http.hostnames }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.gateway.http.rules }}
    - {{- if .matches }}
      matches:
        {{- range .matches }}
        - {{- if .path }}
          path:
            type: {{ .path.type | default "PathPrefix" }}
            value: {{ .path.value | default "/" }}
          {{- end }}
          {{- if .headers }}
          headers:
            {{- range .headers }}
            - type: {{ .type | default "Exact" }}
              name: {{ .name }}
              value: {{ .value }}
            {{- end }}
          {{- end }}
          {{- if .queryParams }}
          queryParams:
            {{- range .queryParams }}
            - type: {{ .type | default "Exact" }}
              name: {{ .name }}
              value: {{ .value }}
            {{- end }}
          {{- end }}
          {{- if .method }}
          method: {{ .method }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- if .filters }}
      filters:
        {{- range .filters }}
        - type: {{ .type }}
          {{- if eq .type "RequestRedirect" }}
          requestRedirect:
            {{- if .requestRedirect.scheme }}
            scheme: {{ .requestRedirect.scheme }}
            {{- end }}
            {{- if .requestRedirect.hostname }}
            hostname: {{ .requestRedirect.hostname }}
            {{- end }}
            {{- if .requestRedirect.port }}
            port: {{ .requestRedirect.port }}
            {{- end }}
            {{- if .requestRedirect.statusCode }}
            statusCode: {{ .requestRedirect.statusCode }}
            {{- end }}
          {{- else if eq .type "URLRewrite" }}
          urlRewrite:
            {{- if .urlRewrite.hostname }}
            hostname: {{ .urlRewrite.hostname }}
            {{- end }}
            {{- if .urlRewrite.path }}
            path:
              type: {{ .urlRewrite.path.type }}
              {{- if .urlRewrite.path.replaceFullPath }}
              replaceFullPath: {{ .urlRewrite.path.replaceFullPath }}
              {{- end }}
              {{- if .urlRewrite.path.replacePrefixMatch }}
              replacePrefixMatch: {{ .urlRewrite.path.replacePrefixMatch }}
              {{- end }}
            {{- end }}
          {{- else if eq .type "RequestHeaderModifier" }}
          requestHeaderModifier:
            {{- if .requestHeaderModifier.set }}
            set:
              {{- range .requestHeaderModifier.set }}
              - name: {{ .name }}
                value: {{ .value }}
              {{- end }}
            {{- end }}
            {{- if .requestHeaderModifier.add }}
            add:
              {{- range .requestHeaderModifier.add }}
              - name: {{ .name }}
                value: {{ .value }}
              {{- end }}
            {{- end }}
            {{- if .requestHeaderModifier.remove }}
            remove:
              {{- range .requestHeaderModifier.remove }}
              - {{ . }}
              {{- end }}
            {{- end }}
          {{- else if eq .type "ResponseHeaderModifier" }}
          responseHeaderModifier:
            {{- if .responseHeaderModifier.set }}
            set:
              {{- range .responseHeaderModifier.set }}
              - name: {{ .name }}
                value: {{ .value }}
              {{- end }}
            {{- end }}
            {{- if .responseHeaderModifier.add }}
            add:
              {{- range .responseHeaderModifier.add }}
              - name: {{ .name }}
                value: {{ .value }}
              {{- end }}
            {{- end }}
            {{- if .responseHeaderModifier.remove }}
            remove:
              {{- range .responseHeaderModifier.remove }}
              - {{ . }}
              {{- end }}
            {{- end }}
          {{- else if eq .type "RequestMirror" }}
          requestMirror:
            backendRef:
              name: {{ .requestMirror.backendRef.name }}
              {{- if .requestMirror.backendRef.namespace }}
              namespace: {{ .requestMirror.backendRef.namespace }}
              {{- end }}
              port: {{ .requestMirror.backendRef.port }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- if .timeouts }}
      timeouts:
        {{- if .timeouts.request }}
        request: {{ .timeouts.request }}
        {{- end }}
        {{- if .timeouts.backendRequest }}
        backendRequest: {{ .timeouts.backendRequest }}
        {{- end }}
      {{- end }}
      backendRefs:
        {{- range .backendRefs }}
        - name: {{ .name | default (include "common.names.fullname" $) }}
          {{- if .namespace }}
          namespace: {{ .namespace }}
          {{- end }}
          port: {{ .port | default $.Values.service.ports.http.port }}
          {{- if .weight }}
          weight: {{ .weight }}
          {{- end }}
        {{- end }}
    {{- end }}
{{- end }}
