{{- if and .Values.gateway.enabled .Values.gateway.tls.enabled }}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: {{ include "common.names.gateway.tlsroute" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if or .Values.gateway.tls.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.gateway.tls.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  {{- include "common.gateway.parentRefs" (dict "gateway" .Values.gateway "context" $) | nindent 2 }}
  {{- if .Values.gateway.tls.hostnames }}
  hostnames:
    {{- range .Values.gateway.tls.hostnames }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  rules:
{{- include "common.gateway.tlsroute.rules" (dict "rules" .Values.gateway.tls.rules "serviceName" (include "common.names.fullname" .) "servicePort" .Values.service.ports.https.port "context" $) | nindent 4 }}
{{- end }}
