## String to partially override fullname template (will maintain the release name)
##
nameOverride: ""

## String to fully override fullname template
##
fullnameOverride: ""

# where the mysql installed namespace
namespaceSelector: monitoring
# jobLabel
jobLabel: "job"
# endports
endpoints: []
# on what port are the metrics exposed by etcd
metricsPortName: metrics
metricsPort: 9113
# Are we talking http or https?
scheme: http
additionalServiceLabels:
  job: "custom"
## Custom Labels to be added to ServiceMonitor
# 经过测试，servicemonitor标签添加prometheus operator的release标签即可正常监控
additionalServiceMonitorLabels:
  release: prometheus-operator
  job: "custom"
##Custom Labels to be added to Prometheus Rules CRD
additionalRulesLabels: 
  release: prometheus-operator

prometheusRule:
  enabled: false
  rules: []
